### PR TITLE
[Dark Theme] badge, indentGuide, lineNumber color

### PR DESCRIPTION
**Pull request by mubaidr**
- Change `badge` notification text to white for better visibility
- Update `indent-guide` and `line-number` color  to more darker color for less distraction.

### CODE REVIEW

**Comment by noudadrichem** [comment]
I'll test this before merge. Straight `#fff` seems a bit straight forward from this point.

**Comment by mubaidr** [comment]
Sure, please. 

Even if not pure white, you can five it little more light color, current color is very matching with the background color.

**Comment by noudadrichem** [comment]
It'll be changed in the next release. If you want it more bright you can change it in your own configurations. 😊

**Comment by mubaidr** [comment]
What about the indent guides and line numbers?

**Comment by noudadrichem** [comment]
Also fixed, you can grab it from the marketplace: https://marketplace.visualstudio.com/items?itemName=Yummygum.city-lights-theme

**Pull request closed without merging**
